### ISSUE TITLE
Pi-hole

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-raspberry-pi#26]
Considering setting up a Pi-hole on the @home network to _eliminate_ ads:
https://github.com/pi-hole/pi-hole
https://en.wikipedia.org/wiki/DNS_sinkhole

# Todo

+ [x] Locate Raspberry Pi 4 and all the accessories needed to run it. 
+ [x] Follow `Pi-hole` tutorial and get it setup
+ [x] Assign Static `IP` on `Unifi Switch`.

**Comment by nelsonic** [comment]
![image](https://github.com/dwyl/learn-raspberry-pi/assets/194400/3f1c8dbf-2611-46e8-b084-86539e0d4308)

![image](https://github.com/dwyl/learn-raspberry-pi/assets/194400/57dac176-4bf1-48bb-a83b-80fa937b7ceb)

**Comment by nelsonic** [comment]
RPi3B booted and is currently updating … 

![IMG_7170](https://github.com/dwyl/learn-raspberry-pi/assets/194400/ede60637-978a-40af-bf13-f4c16109c436)

this might take a while so I’m going back to my desk to do something else …

**Comment by nelsonic** [comment]
I’d forgotten how slow RPi3 is … ⏳

![IMG_7174](https://github.com/dwyl/learn-raspberry-pi/assets/194400/47294849-1096-4368-a38a-c4776f913924)
![IMG_7173](https://github.com/dwyl/learn-raspberry-pi/assets/194400/12a22139-fbf0-43a0-95c9-c2d93e325eae)

**Comment by nelsonic** [comment]
Obvs, but is going to require more effort … 

![IMG_7179](https://github.com/dwyl/learn-raspberry-pi/assets/194400/24ebb854-aac5-4918-8fc1-acf73a7a70f3)

**Comment by nelsonic** [comment]
Configuring static up address on router:
![Uploading IMG_7214.jpeg…]()

**Comment by nelsonic** [comment]
The ISP Router is _garbage_ it does not allow a private DNS on the _internal_ network. 🤦‍♂️

**Comment by nelsonic** [comment]
Starting again from scratch. ⏳ 

![image](https://github.com/dwyl/learn-raspberry-pi/assets/194400/0f59793b-a906-47b5-a05c-78824f1df72a)

**Comment by nelsonic** [comment]
Updating … ⏳🙄

![IMG_7221](https://github.com/dwyl/learn-raspberry-pi/assets/194400/239e43c7-484f-44c0-bd33-c77d3c401ba2)

**Comment by nelsonic** [comment]
Installing … 
![IMG_7222](https://github.com/dwyl/learn-raspberry-pi/assets/194400/4f96a215-2ac1-435f-b7b3-f8f780f1834b)

**Comment by nelsonic** [comment]
Configured and already blocking requests to Ads! 🎉

![IMG_7225](https://github.com/dwyl/learn-raspberry-pi/assets/194400/17639f24-b5a2-48e1-ba48-8b0e03f330e9)

**Comment by nelsonic** [comment]
quick test: visit youtube in **`chrome` _incognito_**

<img width="949" alt="image" src="https://github.com/dwyl/learn-raspberry-pi/assets/194400/562b5ec2-32e1-4f06-a77b-0d2d9e436d2f">

<img width="949" alt="image" src="https://github.com/dwyl/learn-raspberry-pi/assets/194400/1529e1e3-38c1-44be-b222-4dcb6585bc8f">

No ad.

**Comment by nelsonic** [comment]
Need a more comprehensive list ...
https://github.com/Ewpratten/youtube_ad_blocklist
Add: http://gh-pages.ewpratten.com/youtube_ad_blocklist/hosts.ipv4.txt

**Comment by nelsonic** [comment]
I don't usually go _looking_ for websites that have ads on them ... _obvs_ ... 
But the random site I was viewing last week for my research https://github.com/dwyl/home/issues/240#issue-1712141703
is not clean as a whistle. No more annoying/irrelevant ads; just content.
I'm happy.

**Comment by nelsonic** [comment]
Just visited BuzzFeed (notorious for ads): https://www.buzzfeed.com/kristinchirico/surprisingly-gorgeous-homes-made-from-shipping-containers didn't see a single one. 🎉

**Comment by nelsonic** [comment]
By _far_ the biggest advantage of having a DNS server on our internal network is query caching!
It makes the initial page load for the pages we visit frequently _noticeably_ faster. 🐎

**Comment by nelsonic** [comment]
@iteles please confirm if you are seeing ads tomorrow when connected to the `@home` network. 👌

**Comment by nelsonic** [comment]
The `Pi-hole` has been working fine for the past 11 months. ✅ 
Recently moved it to the "closet": https://github.com/dwyl/learn-computer-networking/issues/20
It's using a `Raspberry Pi 3` which is quite "old" at this point. 
But I haven't noticed a delay in accessing any sites. 💭 

Ned a way to monitor it. 📊

**Comment by nelsonic** [comment]
Switched to the MEO network briefly to click on a product link in `Google` SERP (researching a workshop tool)
Then checked the BBC news and see a _massive_ ad for a combustion engine motorcycle:
<img width="1030" alt="image" src="https://github.com/dwyl/learn-raspberry-pi/assets/194400/69c259c0-fb3d-4a4c-a681-df39f4251cfd">

Obviously `Google` Knows my approximate age, gender and income so they are serving me mid-life-crisis motorcycles ... 🤣 
_Love_ `Ducati`, and if I was going to burn non-renewable fossil fuels for thrill-seeking, `Multistrada` for _sure_! 🏍️ 
Switching back to `home` so I don't have to waste my time seeing ads for stuff I'm _never_ gonna buy ... 🙃 

Much sooner buy a [silent yacht](https://silent-yachts.com/) and go sailing around the world! ⛵ 
But they don't _need_ to advertise ... if you can afford it, you know where to find one. 😉 
Anyway ... back to work!!
